# fly.toml file generated for proto-p0 on 2023-01-30T20:19:50+01:00

app = "proto-p0"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 60
    soft_limit = 50
    type = "connections"

  [[services.ports]]
    handlers = []
    port = 8080

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "5s"
